// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veracibot.API.Data;

#nullable disable

namespace Veracibot.API.Migrations
{
    [DbContext(typeof(VeracibotDbContext))]
    [Migration("20250507020311_initial_tweets")]
    partial class initial_tweets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Veracibot.API.Models.Tweets", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("OriginalAuthorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_author_id");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_text");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("thread_id");

                    b.Property<int>("TweetVeracity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tweet_veracity");

                    b.HasKey("Id")
                        .HasName("pk_tweets");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_tweets_author_id");

                    b.HasIndex("OriginalAuthorId")
                        .HasDatabaseName("ix_tweets_original_author_id");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_tweets_thread_id");

                    b.ToTable("tweets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
