// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veracibot.API.Data;

#nullable disable

namespace Veracibot.API.Migrations
{
    [DbContext(typeof(VeracibotDbContext))]
    [Migration("20250507024705_balance")]
    partial class balance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Veracibot.API.Models.AuthorBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<double>("CurrentBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("current_balance");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<double>("PreviousBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("previous_balance");

                    b.Property<string>("TweetId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("tweet_id");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_author_balance");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_author_balance_author_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_author_balance_type");

                    b.ToTable("author_balance", (string)null);
                });

            modelBuilder.Entity("Veracibot.API.Models.TweetAuthor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_tweet_authors");

                    b.HasIndex("UserName")
                        .HasDatabaseName("ix_tweet_authors_user_name");

                    b.ToTable("tweet_authors", (string)null);
                });

            modelBuilder.Entity("Veracibot.API.Models.Tweets", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("OriginalAuthorId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_author_id");

                    b.Property<string>("OriginalText")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_text");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result");

                    b.Property<string>("Text")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("thread_id");

                    b.Property<int>("TweetVeracity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tweet_veracity");

                    b.HasKey("Id")
                        .HasName("pk_tweets");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_tweets_author_id");

                    b.HasIndex("OriginalAuthorId")
                        .HasDatabaseName("ix_tweets_original_author_id");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_tweets_thread_id");

                    b.ToTable("tweets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
