// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VeraciBot.App.Data;

#nullable disable

namespace VeraciBot.App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515101000_TwitterAuthorizationHistory")]
    partial class TwitterAuthorizationHistory
    {
    }
}
